# Generated by Django 2.0.1 on 2018-03-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
