# Generated by Django 2.0.1 on 2018-02-01 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180201_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features_items',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='features_items', to='shop.Features_Items'),
        ),
    ]
