# Generated by Django 2.0.1 on 2018-02-01 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180201_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='products_brand', to='shop.Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='features_items',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Features_Items',
        ),
    ]
