# Generated by Django 2.0.1 on 2018-02-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20180201_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommended_item',
            field=models.BooleanField(default=False),
        ),
    ]
